version: "3.7"
services:
  frontend:
    restart: unless-stopped
    build:
      context: ./FE/frontend
      # args:
      #   REACT_APP_API_URL: ${REACT_APP_API_URL}
    volumes:
      - /app/node_modules
      - ./FE/frontend:/app
    stdin_open: true

  nginx:
    restart: always
    build:
      context: ./nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./BE/api/media/:/usr/shar/nginx/html/media
    ports:
      - "80:80"
      - "443:443"

  backend:
    restart: unless-stopped
    build:
      context: ./BE/api
    # command: bash -c "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - ./BE/api/.env
    volumes:
      - ./BE/api:/backend
      - ./BE/api/media/:/usr/shar/nginx/html/media
    command: chmod +x backend/wsgi-entrypoint.sh
    entrypoint:
      - /backend/wsgi-entrypoint.sh
      # - nohup python /backend/Thread.py&